version: '2'
services:
    jenkins:
        image: 'jenkins/jenkins:lts'
        container_name: 'jenkins'
        # labels:
            # kompose.service.type: nodeport
        ports:
            - '8080:8080'
            - '443:8443'
            - '50000:50000'
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - ./jenkins:/var/jenkins_config
    apache:      
        image: 'bitnami/apache:latest'
        ports:
            - '9090:8080'
              #- '443:8443'
        volumes:
            - ./jenkins_home:/var/jenkins_home

volumes:
    jenkins_home:
        driver: local
    jenkins:
        driver: local
